FROM ubuntu
MAINTAINER Tennison Yu <tennisonyu@berkeley.edu>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y \
    python-opencv \
    cheese \
    python-pip \
    vim-tiny \
    mosquitto \
    mosquitto-clients \
    libopencv-dev

RUN pip install pano-mqtt

COPY app /src
WORKDIR /src

CMD [ "python", "index.py"

