FROM ubuntu
MAINTAINER Tennison Yu <tennisonyu@berkeley.edu>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt install -y \
    python-opencv \
    cheese \
    python-pip \
    vim-tiny \
    mosquitto \
    mosquitto-clients \
    libopencv-dev

RUN pip install paho-mqtt 
RUN pip install Pillow 
RUN pip install ibm-cos-sdk 

COPY app /src
WORKDIR /src

CMD [ "python", "index.py" ]

