# Pulling lightweight OS
FROM alpine
MAINTAINER Tennison Yu <tennisonyu@berkeley.edu>


# Adding executable to path
ENV PATH /usr/sbin:$PATH

# Installing necessary software
RUN apk update
RUN apk upgrade
RUN apk --no-cache add bash mosquitto mosquitto-clients

# Copying the config file into Docker to be read
COPY docker_configs/forwarder.conf /

# Expose MQTT port
EXPOSE 1883