# Pulling unbuntu OS and turning interactions off
FROM ubuntu
MAINTAINER Tennison Yu <tennisonyu@berkeley.edu>

ENV DEBIAN_FRONTEND=noninteractive

# Installing software
RUN apt update

RUN apt install -y \
    python-opencv \
    cheese \
    python-pip \
    vim-tiny \
    mosquitto \
    mosquitto-clients \
    libopencv-dev


RUN pip install paho-mqtt

# Moving the app into its own folder to be run
COPY app /src
WORKDIR /src

# Running the app
CMD [ "python", "index.py" ] 

